spring:
  banner:
    location: "classpath:banner.txt"
  application:
    name: cmetal-be

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER}
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:10000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:20000}

  jpa:
    hibernate:
      ddl-auto: none
      default_schema: ${DEFAULT_SCHEMA}
    show-sql: true
    database-platform: ${HIBERNATE_DIALECT}

  jackson:
    time-zone: Europe/Rome

server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}


logging:
  level:
    org:
      springframework: ${SPRING_LEVEL:INFO}
    com:
      db: ${LOG_LEVEL:DEBUG}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

app:
  images:
    path: ${IMAGES_PATH}
  cors:
    allowed-origins: ${CORS_ALLOWED}

frontend:
  url: ${FRONTEND_URL}


